FROM node:21-alpine3.20

RUN mkdir -p /var/www/api

RUN apk update && apk add --no-cache \
    tzdata \
    docker-cli \
    docker-cli-compose \
    git \
    apache2-utils \
    sed \
    curl

ENV TZ=Europe/Berlin

WORKDIR /var/www/api

COPY ./projects/api/package*.json ./

RUN npm install && npm cache clean --force

COPY ./projects/api ./

RUN npm run build

EXPOSE 3000 4800
