FROM node:21

RUN apt-get update && apt-get install -y \
    libvips-dev \
    build-essential \
    python3 \
    curl \
    tzdata

RUN mkdir -p /var/www

ENV TZ=Europe/Berlin

COPY ./projects/app ./var/www/app

WORKDIR /var/www/app

RUN npm install && npm run build

EXPOSE 3000
